# Xuemei Chen HW1 Python Problems

In [13]:
import numpy as np

### A\. Define a $10\times 10$ matrix $A$ whose entries are the numbers from $1$ to $100$ ordered consecutively going across rows (so $a_{1,1} = 1, a_{2,1} = 11, a_{10,1} = 91$, etc). Let $v = (1, 2, . . . 10)$, and $b = (1, 1, . . . 1)$. Print $A$. Compute $Av$ and solve $Ax = b$ and $Ax = v$ using linalg.solve. Verify your solution by computing $Ax$

In [14]:
A = np.arange(1,101)
A = A.reshape(10,10);print(A)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [15]:
v = np.arange(1,11)
b = np.ones(10)

In [16]:
A@v

array([ 385,  935, 1485, 2035, 2585, 3135, 3685, 4235, 4785, 5335])

In [17]:
np.linalg.solve(A,v)

LinAlgError: Singular matrix

### B. You may get some error in doing above. You decide to "shake" your matrix by some noise, after all data usual comes in noisy.  Use the numpy.random package to build a $10\times 10$ matrix $R(\epsilon)$ whose entries are i.i.d. Gaussian random variables that follow $\text{N}(0,\epsilon^2)$. Verify now that you "can" compute the questions above for various values of $\epsilon>0$ for the new matrix $A+R(\epsilon)$.

In [18]:
def R(e):
    return e*np.random.randn(10,10)    

In [19]:
np.linalg.solve(A + R(0.1),b)

array([-0.09492528,  0.02779942, -0.21539254,  0.12808052,  0.02217797,
        0.07094345, -0.02600824, -0.03241902,  0.15612112, -0.03632473])

In [20]:
np.linalg.solve(A + R(1),v)

array([ 0.00137929,  0.00654457, -0.0323157 ,  0.06940055, -0.02367445,
        0.11466944, -0.04647012, -0.06398003, -0.06755042,  0.14721351])

### C. Write a python function BackSub(A, b) that does the backward substitution from scratch. The input $A$ must be an upper triangular square matrix whose diagonals are all nonzero, and $b$ must be a vector of appropriate dimension. Raise an error if inputs do not satisfy the requirements. It should return the unique solution of solving $Ax=b$.Test your function on 

(a)Problem 3 (b) a 3 by 3 matrix that is not upper triangular (c) a 3 by 2 matrix  (d) Problem 5


In [21]:
# solve Ax=b where A is upper triangular and invertible
def BackSub(A,b):
    m, n = A.shape
    l = len(b)
    if m!=n:
        raise ValueError('The matrix needs to be square')
    if m!=l:
        raise ValueError('Dimensions of A and b do not match.')
    if np.allclose(A, np.triu(A)) == 0: #if not upper triangular
        raise ValueError('A is not upper triangular')
    
    x = np.zeros(n)
    for i in range(n-1,-1,-1): #solve backwards
        if A[i,i] == 0:
            raise ValueError('Your A is not invertible.')
        x[i] = (b[i] - np.sum(x[i+1:]*A[i,i+1:]))/A[i,i]
    return x

In [22]:
# (a)
Aa = np.array([[1,-3,4],[0,1,2],[0,0,1]])
ba = np.array([7,2,5])
np.allclose(BackSub(Aa,ba),np.linalg.solve(Aa,ba))

True

In [23]:
# (b)
Ab = np.array([[1,-3,4],[1,1,2],[0,0,1]])
bb = ba
BackSub(Ab,bb)

ValueError: A is not upper triangular

In [24]:
# (d)
Ad = np.array([[1,-3,7],[0,1,4],[0,0,0]])
bd = np.array([1,0,5])
BackSub(Ad,bd)

ValueError: Your A is not invertible.